ideco/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ItemController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name("homePage");

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});
Route::resource('category',CategoryController::class);
Route::resource('item',ItemController::class);

ideco/app/Models/item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class item extends Model
{
    use HasFactory;
    protected $fillable = [
        'user_id',
        'category_id',
        'img',
        'number',
        'description',
        'name',
        'spesfication_number'
    ];
    
    public function category(): BelongsTo
    {
        return $this->belongsTo(category::class,'category_id');
    }
}

ideco/app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\category;
use App\Models\item;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PhpParser\Node\Stmt\Return_;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $items=item::all();
        return view('items.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories=category::all();
        return view('items.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $input=$request->all();
        $path = $request->file('img')->store('images', 'public');
        $input['img']=$path;
        $input['user_id']=Auth::id();
        item::create($input);
        return redirect()->back()->with('success','تم   بنجاح');   ;

    }

    /**
     * Display the specified resource.
     */
    public function show(item $item)
    {
        return view('items.show',compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(item $item)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, item $item)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(item $item)
    {
        //
    }
}

ideco/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

ideco/resources/views/items/create.blade.php
<x-app-layout>
    <x-slot name="header">
        {{-- <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('ادارة قسم المواصفات') }}
        </h2> --}}
    </x-slot>
    <link rel="stylesheet" href="{{ asset('dist/main.css') }}">

    <div class="py-12">
   
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="col-lg-12 form-area">
                    <form method="POST" action="{{ route('item.store') }}" enctype="multipart/form-data"  >
                        @csrf
                        <div class="row g-3">
                            <div class="col-lg-6">
                                <label for="name">اسم المادة</label>
                                <input type="text" name="name" class="form-control form-control--focused" placeholder="Type here..." id="name" />
                            </div>
                            <div class="col-lg-6">
                                <label for="category">التصنيف</label>
                                <select name="category_id" class="form-control" id="category" style=" padding: 15px;">
                                    @foreach ($categories as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row my-lg-2 my-2">
                            <div class="col-6">
                                <label for="subject">صورة المادة</label>
                                <input type="file" name="img" accept="image/*" id="subject" class="form-control" placeholder="Type here..." />
                            </div> <div class="col-3">
                                <label for="subject"> رقم المادة</label>
                                <input type="text" name="number" id="subject" class="form-control" placeholder="Type here..." />
                            </div>
                            <div class="col-3">
                                <label for="subject"> رقم المواصفة</label>
                                <input type="text" name="spesfication_number" id="subject" class="form-control" placeholder="Type here..." />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <label for="message">وصف المادة</label>
                                <textarea name="description" id="message" placeholder="Type here..." class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="text-end">
                                <button type="submit" class="button button-lg button--primary fw-normal">حفظ </button>
                            </div>
                        </div>
                    </form>
                    <div class="form-area-shape">
                        <img src="dist/images/shape/circle3.png" alt="Shape" class="img-fluid shape-01" />
                        <img src="dist/images/shape/circle5.png" alt="Shape" class="img-fluid shape-02" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

ideco/resources/views/items/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
    <x-nav-link href="{{ route('item.create') }}" :active="request()->routeIs('dashboard')">
        {{ __('create') }}
    </x-nav-link>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg" style="padding: 15px">
                <table id="example" class="display" style="width:100%">
                    <thead>
                        <tr>
                            <th>اسم المادة</th>
                            <th>رقم المادة</th>
                            <th>رقم المواصفة</th>
                            <th> التصنيف</th>
                             <th> حذف</th>
                             <th> تعديل</th>

                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($items as $item)
                        <tr>
                            <td><a href="{{route('item.show',$item) }}"> {{ $item->name}}</a></td>
                            <td>{{ $item->number}}</td>
                            <td>{{ $item->spesfication_number}}</td>
                            <td>{{ $item->category->name}}</td>
                            <td> <form action="{{  route('item.destroy',$item) }}" method="post">
                                @csrf
                                @method("delete")
                                <button type="submit" class ="btn btn-danger  btn-danger ">حذف</button>
                            </form>
                               
                              </td>
                              <td><a href="{{ route('item.edit',$item)}}">تعديل</td>
                            
                        </tr>
                            
                        @endforeach
                       
                     
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>اسم المادة</th>
                            <th>رقم المادة</th>
                            <th>رقم المواصفة</th>
                            <th> التصنيف</th>
                            <th> حذف</th>
                            <th> تعديل</th>
                            
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script>
  new DataTable('#example');
</script>
</x-app-layout>